import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANGUAGE_STORAGE_KEY = 'agroverse_language';

export const LANGUAGE_OPTIONS = [
  { label: 'English', value: 'en' },
  { label: 'हिन्दी', value: 'hi' },
] as const;

export type LanguageCode = typeof LANGUAGE_OPTIONS[number]['value'];
type Translations = Record<LanguageCode, Record<string, string>>;

const TRANSLATIONS: Translations = {
  en: {
    language: 'Language',
    selectLanguage: 'Select Language',
    languageApplied: 'Language updated.',
    logout: 'Logout',
    home: 'Home',
    orders: 'Orders',
    krishiMitra: 'KrishiMitra',
    agroMart: 'AgroMart',
    agroRent: 'AgroRent',
    agriKart: 'AgriKart',
    subtitle: 'Explore the World of Agriculture and Gardening',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    contactNo: 'Contact No',
    address: 'Address',
    success: 'Success',
    error: 'Error',
    sessionExpired: 'Session expired',
    sessionExpiredMessage: 'Your session has expired. Please login again.',
    failedSavedSession: 'Failed to load saved session.',
    authSuccess: '{action} successfully!',
    authToggleLogin: 'Already have an account? Login',
    authToggleRegister: "Don't have an account? Register",
    chatbot: 'ChatBot',
    tutorials: 'Tutorials',
    searchProducts: 'Search Products',
    search: 'Search',
    filterByCategory: 'Filter by Category:',
    all: 'All',
    specialOffers: 'Special Offers & Bulk Deals',
    specialOffersDescription: 'Check out our special deals for bulk purchases and B2B customers!',
    requestQuote: 'Request for Quote',
    quoteSent: 'Request for quote sent for {product}',
    productStore: 'AgroMart - Product Store',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    yourCart: 'Your Cart',
    total: 'Total',
    checkout: 'Checkout',
    close: 'Close',
    deliveryAddress: 'Delivery Address',
    contactNumber: 'Contact Number',
    paymentMode: 'Payment Mode',
    cashOnDelivery: 'Cash on Delivery (COD)',
    onlinePaymentSoon: 'Online Payment (Coming Soon)',
    placeOrder: 'Place Order',
    cancel: 'Cancel',
    orderConfirmed: 'Order Confirmed!',
    enterAddressContact: 'Please enter address and contact details.',
    price: 'Price',
    video: 'Video',
    orderHistory: 'Order History',
    payment: 'Payment',
    items: 'Items',
    noOrders: 'No orders yet.',
    checkoutFailed: 'Could not place your order. Please check your connection and try again.',
    placingOrder: 'Placing order...',
    loadOrdersFailed: 'Could not load your order history. Pull down to retry.',
    equipmentRentals: 'AgroRent Equipment Rentals',
    bookEquipment: 'Book Equipment',
    rentYourEquipment: 'Rent Your Equipment',
    myRentDashboard: 'My Rent Dashboard',
    searchEquipment: 'Search equipment',
    bookNow: 'Book Now',
    rentOutYourEquipment: 'Rent Out Your Equipment',
    equipmentName: 'Equipment Name',
    category: 'Category',
    pricePerDay: 'Price per day (Rs.)',
    description: 'Description',
    imageSelected: 'Image Selected',
    uploadImage: 'Upload Image',
    submitListing: 'Submit Listing',
    myEquipmentListings: 'My Equipment Listings',
    noListingsYet: 'No listings yet.',
    rentRequests: 'Rent Requests',
    noRequestsYet: 'No requests yet.',
    equipment: 'Equipment',
    requestedBy: 'Requested by',
    status: 'Status',
    approve: 'Approve',
    closeDashboard: 'Close Dashboard',
    fetchEquipmentFailed: 'Could not fetch equipment list.',
    requestSent: 'Request Sent!',
    requestSentMessage: 'Your rent request has been sent to the owner.',
    sendRentFailed: 'Could not send rent request.',
    permissionRequired: 'Permission required',
    photoPermissionMessage: 'Please allow access to your photos.',
    fillAllFields: 'Please fill in all fields',
    imageUploadFailed: 'Image Upload Failed',
    uploadImageFailedMessage: 'Could not upload image.',
    listingSuccess: 'Your equipment "{equipment}" is now listed!',
    submitEquipmentFailed: 'Failed to submit equipment. Please try again.',
    fetchDashboardFailed: 'Could not fetch dashboard data.',
    approved: 'Approved',
    approvedMessage: 'Rent request approved.',
    approveFailed: 'Could not approve request.',
    wholesaleB2B: 'AgriKart - Wholesale & B2B',
    fertilizers: 'Fertilizers',
    seeds: 'Seeds',
    pesticides: 'Pesticides',
    machinery: 'Machinery',
    tools: 'Tools',
    tractors: 'Tractors',
    weeders: 'Weeders',
    mowers: 'Mowers',
    sprayers: 'Sprayers',
    powerWeeders: 'Power Weeders',
    lawnMowers: 'Lawn Mowers',
    chainSaws: 'Chain Saws',
    brushCutters: 'Brush Cutters',
    fertilizerX: 'Fertilizer X',
    hybridSeeds: 'Hybrid Seeds',
    pesticideY: 'Pesticide Y',
    waterPumpZ: 'Water Pump Z',
    tractor: 'Tractor',
    krishiTitle: 'KrishiMitra - Your Smart Farming Companion',
    cropAdvisory: 'AI Crop Advisory',
    selectCrop: 'Select Crop:',
    selectSoil: 'Select Soil Type:',
    getRecommendations: 'Get Recommendations',
    missingSelection: 'Please select both crop and soil type.',
    pestDetection: 'Pest/Disease Detection',
    uploadPlantImage: 'Upload Plant Image',
    seasonalCalendar: 'Seasonal Crop Calendar',
    calendarDescription: 'Select your state to view sowing/harvesting months and crops.',
    selectState: 'Select State:',
    showCropCalendar: 'Show Crop Calendar',
    noCalendarData: 'No data found for this state.',
    calendarError: 'Error loading crop calendar.',
    weatherTitle: 'Live Weather Updates',
    weatherDescription: 'Location-based real-time weather info.',
    checkWeather: 'Check Weather',
    loading: 'Loading...',
    pricesTitle: 'Crop Price Trends',
    pricesDescription: 'See real-time mandi prices and trends.',
    viewPrices: 'View Prices',
    newsTitle: 'Agri News Feed',
    readLatestNews: 'Read Latest News',
    chatbotTitle: 'Chatbot Advisor',
    talkToChatbot: 'Talk to Chatbot',
    voiceTitle: 'Voice-Based Tips',
    playAdvice: 'Play Advice',
    applyLanguage: 'Apply Language',
    cropPrices: 'Crop Prices',
    filterState: 'Filter by State:',
    filterCommodity: 'Filter by Commodity:',
    agriNews: 'Agri News',
    noNews: 'No news found.',
    noPriceData: 'No data available.',
    permissionDenied: 'Permission Denied',
    permissionMessage: 'Location permission is required for weather updates.',
    locationUnavailable: 'Location not available',
    locationMessage: 'Please allow location access.',
    weatherFailed: 'Unable to fetch weather data.',
    newsFailed: 'Unable to fetch news. Please try again later.',
    uploadTitle: 'Upload',
    uploadMessage: 'Image picker for pest/disease detection will be added.',
    chatbotMessage: 'AI chatbot in development.',
    voiceMessage: 'Voice tips will play.',
    kharifSeason: 'Kharif Season',
    rabiSeason: 'Rabi Season',
    months: 'Months',
    crops: 'Crops',
    market: 'Market',
    district: 'District',
    state: 'State',
    date: 'Date',
    min: 'Min',
    max: 'Max',
    modal: 'Modal',
    location: 'Location',
    weather: 'Weather',
    temperature: 'Temperature',
    humidity: 'Humidity',
  },
  hi: {
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    languageApplied: 'भाषा अपडेट हो गई।',
    logout: 'लॉग आउट',
    home: 'होम',
    orders: 'ऑर्डर',
    krishiMitra: 'कृषिमित्र',
    agroMart: 'एग्रोमार्ट',
    agroRent: 'एग्रोरेंट',
    agriKart: 'एग्रीकार्ट',
    subtitle: 'कृषि और बागवानी की दुनिया देखें',
    login: 'लॉग इन',
    register: 'रजिस्टर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    contactNo: 'संपर्क नंबर',
    address: 'पता',
    success: 'सफलता',
    error: 'त्रुटि',
    sessionExpired: 'सेशन समाप्त',
    sessionExpiredMessage: 'आपका सेशन समाप्त हो गया है। कृपया फिर से लॉग इन करें।',
    failedSavedSession: 'सेव किया गया सेशन लोड नहीं हो सका।',
    authSuccess: '{action} सफल!',
    authToggleLogin: 'पहले से अकाउंट है? लॉग इन करें',
    authToggleRegister: 'अकाउंट नहीं है? रजिस्टर करें',
    chatbot: 'चैटबॉट',
    tutorials: 'ट्यूटोरियल',
    searchProducts: 'उत्पाद खोजें',
    search: 'खोजें',
    filterByCategory: 'श्रेणी से फिल्टर करें:',
    all: 'सभी',
    specialOffers: 'विशेष ऑफर और बल्क डील',
    specialOffersDescription: 'बल्क खरीद और B2B ग्राहकों के लिए खास डील देखें।',
    requestQuote: 'कोटेशन मांगें',
    quoteSent: '{product} के लिए कोटेशन अनुरोध भेजा गया',
    productStore: 'एग्रोमार्ट - उत्पाद स्टोर',
    addToCart: 'कार्ट में जोड़ें',
    buyNow: 'अभी खरीदें',
    yourCart: 'आपका कार्ट',
    total: 'कुल',
    checkout: 'चेकआउट',
    close: 'बंद करें',
    deliveryAddress: 'डिलीवरी पता',
    contactNumber: 'संपर्क नंबर',
    paymentMode: 'भुगतान मोड',
    cashOnDelivery: 'कैश ऑन डिलीवरी (COD)',
    onlinePaymentSoon: 'ऑनलाइन भुगतान (जल्द)',
    placeOrder: 'ऑर्डर करें',
    cancel: 'रद्द करें',
    orderConfirmed: 'ऑर्डर कन्फर्म हो गया!',
    enterAddressContact: 'कृपया पता और संपर्क जानकारी दर्ज करें।',
    price: 'कीमत',
    video: 'वीडियो',
    orderHistory: 'ऑर्डर इतिहास',
    payment: 'भुगतान',
    items: 'आइटम',
    noOrders: 'अभी कोई ऑर्डर नहीं।',
    checkoutFailed: 'ऑर्डर देने में समस्या हुई। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    placingOrder: 'ऑर्डर दिया जा रहा है...',
    loadOrdersFailed: 'ऑर्डर इतिहास लोड नहीं हो सका। पुनः प्रयास के लिए नीचे खींचें।',
    equipmentRentals: 'एग्रोरेंट उपकरण किराया',
    bookEquipment: 'उपकरण बुक करें',
    rentYourEquipment: 'अपना उपकरण किराए पर दें',
    myRentDashboard: 'मेरा किराया डैशबोर्ड',
    searchEquipment: 'उपकरण खोजें',
    bookNow: 'अभी बुक करें',
    rentOutYourEquipment: 'अपना उपकरण सूचीबद्ध करें',
    equipmentName: 'उपकरण का नाम',
    category: 'श्रेणी',
    pricePerDay: 'प्रति दिन कीमत (रु.)',
    description: 'विवरण',
    imageSelected: 'छवि चुनी गई',
    uploadImage: 'छवि अपलोड करें',
    submitListing: 'लिस्टिंग सबमिट करें',
    myEquipmentListings: 'मेरी उपकरण लिस्टिंग',
    noListingsYet: 'अभी कोई लिस्टिंग नहीं।',
    rentRequests: 'किराया अनुरोध',
    noRequestsYet: 'अभी कोई अनुरोध नहीं।',
    equipment: 'उपकरण',
    requestedBy: 'अनुरोधकर्ता',
    status: 'स्थिति',
    approve: 'स्वीकृत करें',
    closeDashboard: 'डैशबोर्ड बंद करें',
    fetchEquipmentFailed: 'उपकरण सूची नहीं मिल सकी।',
    requestSent: 'अनुरोध भेजा गया!',
    requestSentMessage: 'आपका किराया अनुरोध मालिक को भेज दिया गया है।',
    sendRentFailed: 'किराया अनुरोध नहीं भेजा जा सका।',
    permissionRequired: 'अनुमति आवश्यक',
    photoPermissionMessage: 'कृपया फोटो एक्सेस की अनुमति दें।',
    fillAllFields: 'कृपया सभी फील्ड भरें',
    imageUploadFailed: 'छवि अपलोड विफल',
    uploadImageFailedMessage: 'छवि अपलोड नहीं हो सकी।',
    listingSuccess: 'आपका उपकरण "{equipment}" अब सूचीबद्ध है!',
    submitEquipmentFailed: 'उपकरण सबमिट नहीं हो सका। कृपया फिर कोशिश करें।',
    fetchDashboardFailed: 'डैशबोर्ड डेटा नहीं मिल सका।',
    approved: 'स्वीकृत',
    approvedMessage: 'किराया अनुरोध स्वीकृत।',
    approveFailed: 'अनुरोध स्वीकृत नहीं हो सका।',
    wholesaleB2B: 'एग्रीकार्ट - थोक और B2B',
    fertilizers: 'खाद',
    seeds: 'बीज',
    pesticides: 'कीटनाशक',
    machinery: 'मशीनरी',
    tools: 'उपकरण',
    tractors: 'ट्रैक्टर',
    weeders: 'वीडर',
    mowers: 'मोवर',
    sprayers: 'स्प्रेयर',
    powerWeeders: 'पावर वीडर',
    lawnMowers: 'लॉन मोवर',
    chainSaws: 'चेन सॉ',
    brushCutters: 'ब्रश कटर',
    fertilizerX: 'खाद X',
    hybridSeeds: 'हाइब्रिड बीज',
    pesticideY: 'कीटनाशक Y',
    waterPumpZ: 'वॉटर पंप Z',
    tractor: 'ट्रैक्टर',
    krishiTitle: 'कृषिमित्र - आपका स्मार्ट खेती साथी',
    cropAdvisory: 'AI फसल सलाह',
    selectCrop: 'फसल चुनें:',
    selectSoil: 'मिट्टी का प्रकार चुनें:',
    getRecommendations: 'सलाह पाएं',
    missingSelection: 'कृपया फसल और मिट्टी दोनों चुनें।',
    pestDetection: 'कीट/रोग पहचान',
    uploadPlantImage: 'पौधे की फोटो अपलोड करें',
    seasonalCalendar: 'मौसमी फसल कैलेंडर',
    calendarDescription: 'बुवाई/कटाई के महीने और फसलें देखने के लिए अपना राज्य चुनें।',
    selectState: 'राज्य चुनें:',
    showCropCalendar: 'फसल कैलेंडर दिखाएं',
    noCalendarData: 'इस राज्य के लिए डेटा नहीं मिला।',
    calendarError: 'फसल कैलेंडर लोड करने में त्रुटि।',
    weatherTitle: 'लाइव मौसम अपडेट',
    weatherDescription: 'स्थान आधारित रियल-टाइम मौसम जानकारी।',
    checkWeather: 'मौसम देखें',
    loading: 'लोड हो रहा है...',
    pricesTitle: 'फसल मूल्य रुझान',
    pricesDescription: 'रियल-टाइम मंडी कीमतें और रुझान देखें।',
    viewPrices: 'कीमतें देखें',
    newsTitle: 'कृषि समाचार',
    readLatestNews: 'ताजा समाचार पढ़ें',
    chatbotTitle: 'चैटबॉट सलाहकार',
    talkToChatbot: 'चैटबॉट से बात करें',
    voiceTitle: 'आवाज आधारित सुझाव',
    playAdvice: 'सलाह सुनें',
    applyLanguage: 'भाषा लागू करें',
    cropPrices: 'फसल कीमतें',
    filterState: 'राज्य से फिल्टर करें:',
    filterCommodity: 'कमोडिटी से फिल्टर करें:',
    agriNews: 'कृषि समाचार',
    noNews: 'कोई समाचार नहीं मिला।',
    noPriceData: 'डेटा उपलब्ध नहीं है।',
    permissionDenied: 'अनुमति अस्वीकृत',
    permissionMessage: 'मौसम अपडेट के लिए लोकेशन अनुमति जरूरी है।',
    locationUnavailable: 'लोकेशन उपलब्ध नहीं',
    locationMessage: 'कृपया लोकेशन एक्सेस की अनुमति दें।',
    weatherFailed: 'मौसम डेटा प्राप्त नहीं हो सका।',
    newsFailed: 'समाचार प्राप्त नहीं हो सके। कृपया बाद में प्रयास करें।',
    uploadTitle: 'अपलोड',
    uploadMessage: 'कीट/रोग पहचान के लिए इमेज पिकर जोड़ा जाएगा।',
    chatbotMessage: 'AI चैटबॉट विकास में है।',
    voiceMessage: 'आवाज सुझाव चलेंगे।',
    kharifSeason: 'खरीफ मौसम',
    rabiSeason: 'रबी मौसम',
    months: 'महीने',
    crops: 'फसलें',
    market: 'मंडी',
    district: 'जिला',
    state: 'राज्य',
    date: 'तारीख',
    min: 'न्यूनतम',
    max: 'अधिकतम',
    modal: 'मोडल',
    location: 'स्थान',
    weather: 'मौसम',
    temperature: 'तापमान',
    humidity: 'नमी',
  },
};

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  tr: (key: string, values?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_STORAGE_KEY)
      .then((savedLanguage) => {
        if (savedLanguage === 'en' || savedLanguage === 'hi') {
          setLanguageState(savedLanguage);
        }
      })
      .catch(() => undefined);
  }, []);

  const setLanguage = useCallback((nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage).catch(() => undefined);
  }, []);

  const tr = useCallback(
    (key: string, values: Record<string, string | number> = {}) => {
      let text = TRANSLATIONS[language][key] || TRANSLATIONS.en[key] || key;
      Object.entries(values).forEach(([name, value]) => {
        text = text.replace(new RegExp(`\\{${name}\\}`, 'g'), String(value));
      });
      return text;
    },
    [language]
  );

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    tr,
  }), [language, setLanguage, tr]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
